version: '2'
services:
  coffee:
    build: ./docker/coffee
    volumes:
      - ".:/expense-tracker/"
    links:
      - mongo
    ports:
      - "4000:4000"
  mongo:
    build: ./docker/mongo
    environment:
    - ENV
    - MONGODB_USERNAME=user
    - MONGODB_PASSWORD=password
    - MONGODB_DBNAME=expense-tracker
    volumes:
      - "./data/:/data/"
    ports:
      - "27017:27017"