version: '2'
services:
  coffee:
    build: ./docker/coffee
    environment:
      - ENV
      - DB_URL_MONGO=mongodb://mongo:27017/data
    volumes:
      - ".:/expense-tracker/"
    links:
      - mongo
  mongo:
      build: ./docker/mongo
      environment:
      - ENV
      - MONGODB_USERNAME=user
      - MONGODB_PASSWORD=password
      - MONGODB_DBNAME=expense-tracker
      volumes:
        - "./data/:/data/"
      ports:
        - "27017:27017"